### ISSUE TITLE
ckan-cloud-operator should support Azure DNS provider

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#112]
CCO supports Cloudflare and AWS Route53 for registering DNS for CKAN applications. We need it to support Azure-DNS as well.

When CCO users deploy CKAN infra in azure environmen, they wants to register DNS records for their CKAN apps on Azure-DNS, so that they have all infra under their azure account.

When I want to create DNS record for my CKAN app (with CCO), I want it on Azure-DNS, so that I can use my azure account, cause that's what I like.

## Acceptance Criteria

- [x] CCO suports Azure-DNS as a provider.
- [x] My CKAN App has DNS record on Azure-DNS after I deploy the app, or create route.
- [x] Documnted how to.

## Tasks

- [x] Read about Azure-DNS, API Docs
- [x] Read CCO code and how the similar is done for CloudFlare and Route54
- [x] Do analysis and plan the work
- [ ] ...

## Analysis

WIP

Docs: https://docs.microsoft.com/en-us/azure/dns/dns-overview

> Azure DNS is a hosting service for DNS domains that provides name resolution by using Microsoft Azure infrastructure. By hosting your domains in Azure, you can manage your DNS records by using the same credentials, APIs, tools, and billing as your other Azure services.

**Note:**
>You can't use Azure DNS to buy a domain name. For an annual fee, you can buy a domain name by using App Service domains or a third-party domain name registrar. Your domains then can be hosted in Azure DNS for record management. For more information, see Delegate a domain to Azure DNS.

**Comment by pwalsh** [comment]
@akariv @zelima is this in a state for me to do acceptance testing yet?

**Comment by zelima** [comment]
Still needs to be merged  https://github.com/datopian/ckan-cloud-operator/pull/115

**Comment by zelima** [comment]
FIXED
