### ISSUE TITLE
Support pulling images from private container registries

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#120]
Currently, we only support deis instances to be pulled from private registries https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/ckan/manager.py#L29

We need it to be enabled for any instance.

## Acceptance Criteria

- [x] Able to create instance that has image on private container registry (Eg gitlab)

## Task

- [x] refactor ckan/manager.py to do that other than deis instance https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/ckan/manager.py#L29
- [x] Accept registry credentials from interactive mode (also from interactive.yaml)
- [x] Test it is working

**Comment by zelima** [comment]
FIXED in https://github.com/datopian/ckan-cloud-operator/commit/a65253841b9879e7ac91cea4234264de238adb8a
