### ISSUE TITLE
cco ckan instance create helm does not terminate if failed creating solr collection

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#122]
I run
```
ckan-cloud-operator ckan instance create helm --instance-id abc --instance-name abc --update my-values.yaml
```

If for whatever reasons solr collection is not created, I see logs saying it failed but cco continues deployment, and may even succeed. But at the end CKAN instance is not working cause there is no SOLR collection for it 

## Acceptance Criteria

- [ ] I'm sure SOLR collection is created or failed for instance

## Tasks

- [ ] Check if failed and retry couple time
- [ ] Exit with non 0 if failed with proper message

**Comment by zelima** [comment]
Think this is a long time FIXED
