### ISSUE TITLE
[Docs] What is values.yaml file and how to properly write it 

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#73]
Helm based deployment assumes that user already has `values.yaml` when deploying to k8 with helm. 

As a newbie CCO user, I want to know what exactly values.yaml is, what it is for, if it is required and how to create it (and maybe have an example of it) so that I'm able to perform helm based deployments.

As a CCO user, I want to know what is the conversion of writing values there, EG how would `ckan.storaga_path` should be written there, so that I'm able to set CKAN configurations in it.

As a CCO user, I want to know what other values can be set and what they are for, Eg `replicas` ,  `terminationGracePeriodSeconds` etc.. so that I know what I'm doing when I'm creating values.yaml

## Acceptance Criteria

- [x] We have a separate section in docs dedicated to values.yaml
- [ ] I'm (or somebody from the team) is able to create it and deploy CKAN instance

## Tasks

- [ ] Gather the need info and answer the user stories and 
- [ ] Write the README

**Comment by pwalsh** [comment]
@akariv @zelima is this in a state for me to do acceptance testing yet?

**Comment by zelima** [comment]
I think yes https://github.com/datopian/ckan-cloud-operator/blob/master/docs/VALUES-FILE-REFERENCE.md
