### ISSUE TITLE
Create storage classes with CCO

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#75]
As a cco user, who does not know much about storage-classes, I want cco to take care of its creation,  so that I don't need to spend time understanding what they are and how to configure them properly

As a cco user, I want to be able to configure storage-classes Eg choose which provisioner to use (azure, aws, google etc...), so that I'm able to use cloud provider of my choice

As a cco user, I want to have a general understanding of what storage-classes are and what they are for so that I'm able to configure properly

## Acceptance criteria

- [ ] Have small description of what storage classes are  (maybe in command help or readme)
- [ ] cco creates storage-classes for me if I don't specify
- [ ] cco give me the ability to configure storage classes (eg prompts me with proper questions)

## Tasks

- [ ] Do analysis
- [ ] Write small description/doc about what it is for and here to read more
- [ ] Refactor code to address user stories

**Comment by akariv** [comment]
I added this for the minikube flow - shouldn't be difficult to replicate (more or less...) for the other providers.

**Comment by pwalsh** [comment]
@akariv @zelima was this done for other providers, and, can you link me to the relevant part of code and docs so i can do acceptance checks?

**Comment by zelima** [comment]
@pwalsh
- AWS https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/cluster/aws/manager.py#L64-L86
- Gcloud https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/cluster/gcloud/manager.py#L132-L151
- Minikube https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/cluster/minikube/manager.py#L41-L53
- Azure (not yer merged) https://github.com/datopian/ckan-cloud-operator/blob/azure-integration-terraform/ckan_cloud_operator/providers/cluster/azure/manager.py#L80-L107
