### ISSUE TITLE
Handle different versions of helm on different clusters

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#76]
As a cco user trying to deploy with helm, I had to reinstall helm version on my local machine every time I switched between clusters (azrure, ckan-cloud, minikube), cause different versions if it were installed on each of them.

As a cco user, I want that to be handled efficiently Eg: cco checks for helm version on a cluster and asks me to run `cco helm init` or similar, and installs the proper version of it locally (or maybe re-installs latest version on both sides)

## Acceptance Criteria

- [ ] I don't have to manually install helm every time there is inconsistency

## Tasks

- [ ] Do analysis decide if we can handle this (is it worth spending time at all?)
- [ ] Propose solution if reasonable
