### ISSUE TITLE
Enable database initialization inside minikube

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#87]
I'm trying to initialize cluster in minikube but only allowed providers are Gcloud and AWS https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/cluster/manager.py#L61

```
def initialize(log_kwargs=None, interactive=False, default_cluster_provider=None, skip_to=None):
    ...
    assert default_cluster_provider in ['gcloud', 'aws'], f'invalid cluster provider: {default_cluster_provider}'
```

## Acceptance Criteria

- [ ] I'm allowed to use local postgres for minikube instance
- [ ] At least initialize does not fail

## Tasks

- [ ] Find out where else cluster providers are used and list out what we need to refactor besides the assert part 
- [ ] Create the `manager` for minkube/local Postgres database
- [ ] Create `proxy.manager` for minkube/local Postgres database
  - [ ] understand how `_apply_deployment` works for each of aws and gcloud and think how it should look like for minkube/local
    - [ ] Maybe ask Mikhail for help
- [ ] Create a method that will create database instance (does not exist currently anywhere as both aws and gcloud assume that DB instance is already created)

## Analysis

db_manager.initialize seems to be quite depended on that variable. Seems like we need quite big refactor to allow this happen https://github.com/datopian/ckan-cloud-operator/blob/master/ckan_cloud_operator/providers/db/manager.py#L15-L29
```
def initialize(log_kwargs=None, interactive=False, default_cluster_provider=None):
    """Initialize / upgrade the db module and sub-modules"""
    if default_cluster_provider == 'aws':
        default_provider = db_rds_provider_id
    elif not default_cluster_provider or default_cluster_provider == 'gcloud':
        default_provider = db_gcloudsql_provider_id
    else:
        raise NotImplementedError(f'Unknown provider: {default_cluster_provider}')
    log_kwargs = log_kwargs or {}
    logs.info(f'Initializing DB provider', **log_kwargs)
    db_provider = providers_manager.get_provider(db_provider_submodule, default=default_provider)
    db_provider.initialize(interactive=interactive)
    if db_provider.is_private_ip():
        logs.info('DB Uses a private ip, initializing the DB proxy')
        db_proxy_manager.initialize()
```

### Acions

- [x] Understand the code for existing providers and how they work.
- [x] Run db initialize only for development...
  - [ ] Write a small script to initialize db's only
  - [x] Or maybe I can do that with CLI?

### Questions

Q: How can I run db initialization part only? (don't want to initialize the whole cluster every time)
A: run `ckan-cloud-operator db initialize`

Q: What are `db_rds_provider_id` and `db_gcloudsql_provider_id` and `db_provider_submodule`?
A:
- `db_provider_submodule` is hardcoded to `db`
- `db_gcloudsql_provider_id` is hardcoded to `gcloudsql`
- `db_rds_provider_id` is hardcoded to `rds`

Q: And what `pdovider_id` should be set for minikube?
A: Think it's safe to set it to `mk` (or anything if necessary), basically does not really matter ATP.

Q: How does exactly `get_provider` works and how can it be used in case of Minikube
A: It basically gets appropriate db_manager. Eg If we use AWS RDS instance it will return `porviders.rds.manager` and `porviders.gcloudsql.manager` else. We will need to refactor so that logic so that it also handles local/minkube Postgres manager...

Q: What does `db_prvider.initialize()` method exactly do for each provider.
  - What differences they have?
  - What they have common?

A1: The deferences are 
- `default_values` (see example a bit below), 
- each of them has it's own proxy manager 
- they have different ways to get ports
A2: Everything else is identical

Example of `default_values`
```python=
# GCLOUD
default_values = {
  'host': '',
  'port': '5432',
  'is-private-ip': True,
  'admin-user': '',
  'admin-password': '',
  'gcloud-sql-instance-name': '',
}

## RDS
default_values = {
  'rds-instance-name': '',
  'rds-host': '',
  'admin-user': '',
  'admin-password': ''
}
```

Q: What does `proxy.manager`s do? What are common and different?
A: Everything is identical here as well exactly the `_apply_deployment` methods that have their own specifications...

**Comment by pwalsh** [comment]
@akariv @zelima is this still relevant?

**Comment by zelima** [comment]
No, the cluster is initialized on minikube without any errors
